language: php

php:
  - 7.3
  - 7.4

before_install:
  - SYMFONY_DEPENDENCIES=$(cat composer.json | jq '.require | to_entries[] | "\(.key):\(.value)"' | egrep -o '(symfony\/[^:]+)[^|]+\|' | egrep -o '(symfony\/[^:]+)'); for SYMFONY_DEPENDENCY in $SYMFONY_DEPENDENCIES; do composer require "${SYMFONY_DEPENDENCY}:${SYMFONY_VERSION}" --no-update; done

install: composer install --no-interaction

script:
  - composer run-coverage

env:
  global:
    - CC_TEST_REPORTER_ID=9b04e6d1240f2bbeca64987ce2453431b818f548cfa0d8465955469091ab4a2b
    - SYMFONY_VERSION=^4.3

matrix:
  include:
    - php: 7.3
      env: SYMFONY_VERSION=^3.4
    - php: 7.4
      env: SYMFONY_VERSION=^3.4

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - mv tests/_output/coverage.xml clover.xml
  - ./cc-test-reporter after-build --coverage-input-type clover --id $CC_TEST_REPORTER_ID --exit-code $TRAVIS_TEST_RESULT

notifications:
  slack:
    rooms:
      secure: VP7hOQ5r3tHzAeoKJPP93zCBWzHsUXKWS4QnwPqxR/UDKIRiEZp+BAKCG2GApHpwIOQnyJWOf7Mjp8vKpwHl1DeSVvS/s8FYg7UuVuRZjg0D3GKEKHhRrmFlS9MmjsS2S3Id23TlAWNfSrpQ/KvrVDQp2R1AerPmxpvnPKKpjNiSdvmXefrcPIFiiAQopE2NUiO/zIu+41AT1t4e2qJvN8LRQWE0/goiM23QqlTtBL22IP+Ia3EtjhiBlAXGFrGUC7i2yHWA+K+3eSJ8bUB4vtYE63l8uqQrMRgNhRckTwATCA0XzUEJKz9hyvQDc0Km0IwWG90TlgxbZ6w6Hdu+Os9KEpp2f9MjiyFgZrqIh2YArWa0Y2YECzpNuTMy48VmEizG2wOf7ykg1FzaE4DjQfamnLi3MyMzgZFpM89LpKYuXjSEB9vVQL98AlUKyS1jPb3o5Neu54osfsHm4Cv55sgBZO9NdCwhUQr3RdElvCgeoFCphvD0YHGnQt7JwYYjKBkmho8Yz53YOymERh80AJLWPVkFv8gnXCT2mHbfnygsIQg0BHDwOd1/n8IX+YGrPaMf87qSNgiJJFG8oCuUe2E3QsU8EfZupKVhY2RGJC5t3VQdep6dElg4eL6fqwhqEhu5YhlMYXk0cirqKhzVSimdXA036alY7cvkLLjx7ic=
