language: php

php:
  - 7.3

install: composer install --no-interaction

script:
  - composer run-coverage

env:
  global:
    - CC_TEST_REPORTER_ID=9b04e6d1240f2bbeca64987ce2453431b818f548cfa0d8465955469091ab4a2b

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - mv tests/_output/coverage.xml clover.xml
  - ./cc-test-reporter after-build --coverage-input-type clover --id $CC_TEST_REPORTER_ID --exit-code $TRAVIS_TEST_RESULT
